# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation

name: Metrics

on:
  # Update once a day at 00:00 UTC
  schedule:
    - cron: '0 0/24 * * *'
  workflow_dispatch:

jobs:
  render-metrics:
    runs-on: ubuntu-latest
    steps:
      # 0️⃣ Checkout (so the action can commit)
      - name: Checkout
        uses: actions/checkout@v3

      # 1️⃣ Fortune
      - name: Render Fortune
        uses: lowlighter/metrics@v3.36
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: America/New_York

          # only Fortune
          plugin_fortune: yes

          # commit back to your metrics-renders branch
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"

      # 2️⃣ WakaTime stats
      - name: Render WakaTime Stats
        uses: lowlighter/metrics@v3.36
        with:
          filename: wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: America/New_York

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os

          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"

      # 3️⃣ General overview (calendar, languages, notable, discussions, topics, stargazers, traffic)
      - name: Render General Metrics
        uses: lowlighter/metrics@v3.36
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community
          config_timezone: America/New_York
          base_indepth: yes
          config_order: |
            base.header,
            isocalendar,
            languages,
            notable,
            discussions,
            topics,
            stargazers,
            traffic

          # ─── Calendar ─────────────────────────────────────────────────────
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # ─── Languages ───────────────────────────────────────────────────
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

          # ─── Topics & Notable & Discussions ──────────────────────────────
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes

          # ─── Stargazers ─────────────────────────────────────────────────
          plugin_stargazers: yes
          plugin_stargazers_days: 14

          # ─── Traffic ────────────────────────────────────────────────────
          plugin_traffic: yes

          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"
          
