# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation

name: Metrics
on:
  # Update once a day at 00:00 UTC
  schedule:
    - cron: '0 0/24 * * *'
  # Allow manual runs
  workflow_dispatch:

jobs:
  render-metrics:
    name: Render Metrics
    runs-on: ubuntu-latest
    steps:
      # 3️⃣ Achievements & Fortune
      - name: Render Achievements & Fortune
        uses: lowlighter/metrics@v3.34
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # ─── Base settings ──────────────────────────────────────────────────
          base: ""
          config_timezone: America/New_York
          template: classic

          # ─── Commit settings ──────────────────────────────────────────────────
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"

          # ─── Gists plugin ───────────────────────────────────────────────────────
          plugin_gists: yes

          # ─── Star lists plugin ────────────────────────────────────────────────
          plugin_starlists: yes                     # enable star lists
          plugin_starlists_limit: 3                 # how many lists to display (default: 2)
          plugin_starlists_limit_repositories: 6    # repos per list (default: 2)

          # ─── Fortune plugin ───────────────────────────────────────────────────
          plugin_fortune: yes

      # 3️⃣➕ WakaTime Stats (right under Achievements)
      - name: Render WakaTime Stats
        uses: lowlighter/metrics@v3.34
        with:
          filename: wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: America/New_York

          # ─── Commit settings ──────────────────────────────────────────────────
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"

          # ─── WakaTime plugin ──────────────────────────────────────────────────
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os

      # 4️⃣ General overview (calendar, languages, notable, discussions, topics, stargazers, lines, traffic)
      - name: Render General Metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community
          config_timezone: America/New_York
          base_indepth: yes
          config_order: |
            base.header,
            isocalendar,
            languages,
            notable,
            discussions,
            topics,
            stargazers,
            traffic

          # ─── Calendar ─────────────────────────────────────────────────────────
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # ─── Languages ────────────────────────────────────────────────────────
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

          # ─── Topics, Notable & Discussions ───────────────────────────────────
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes

          # ─── Stargazers ───────────────────────────────────────────────────────
          plugin_stargazers: yes
          plugin_stargazers_days: 14

          # ─── Traffic ──────────────────────────────────────────────────────────
          plugin_traffic: yes
